### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by WangzoR** [princesslana/ErisCasper.java#108]
Overview of content and supporting pages that need to be created for and linked

When starting work on the project, please go through the following.

Must Have

- [ ]     Project Overview/Oversight Page?
                Key milestones?
                Targets?
                What is classified as MVP for official discord status consideration?
                https://discordapi.com/unofficial/comparison.html?
                Outstanding epics?

Must Have

- [ ] 	   Install the project on your computer (links to "Setting up the project locally page")
		Access
		Software/Framework/Lib Dependencies
		Source file locations/info
		Setup Guide per IDE/environment 
		Setup Common Pitfalls
		Localised running/testing?

- [ ]     Read up on the project (links to "About the Project page(s)")
		Discord
		DiscordAPI
		Vision/Goal
		ReactiveX 
		Architecture Overview
		Milestones/Phases
		Timeline?
		Project Goverance/Structure
		Team/Go To People/Contributors
		
Should Have   

- [ ] 	If you are not familiar with ReactiveX/Java or could use a refresher
                Please make sure to familiarise yourself ( Links to externally hosted ReactiveX guides)
                Link to official ReactiveX pages
		Tutorials/Guides
		Examples
		
- [ ] 	Read and understand the coding guidelines / standards  (Links to "Coding Standards")
		White Space
		Naming Convention
                Java Style Guide

Could Have    

- [ ] 	Read and understand the development process (Links to "Development & Work Process")
		Logging Issues Guidelines
		Picking Up Issues and progression Guidelines
		Labels Usage
		Branching Methodology
		Pull Request Guidelines
		Unit testing
	
Reference material
![reimport-maven-intellij](https://user-images.githubusercontent.com/37465280/37871666-172a9246-303f-11e8-9423-4d9fd10faf9f.png)
https://github.com/twitter/commons/blob/master/src/java/com/twitter/common/styleguide.md
http://reactivex.io/
http://reactivex.io/intro.html	
https://princesslana.github.io/ErisCasper.java/
https://gist.github.com/meew0/bbbbd5348967dee5f7e84c0cd58983fd
https://immutables.github.io/apt.html
https://github.com/princesslana/ErisCasper.java/tree/master/src/site/markdown
https://github.com/princesslana/ErisCasper.java/blob/master/src/site/site.xml#L9
https://github.com/WangzoR/ErisCasper.java/blob/master/ISSUE_TEMPLATE.md
https://github.com/WangzoR/ErisCasper.java/blob/master/CONTRIBUTING.md
https://github.com/WangzoR/ErisCasper.java/blob/master/CODE_OF_CONDUCT.md
https://github.com/WangzoR/ErisCasper.java/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by ianagbip1oti** [comment]
Regarding code style, there is a section in https://github.com/princesslana/ErisCasper.java/blob/master/CONTRIBUTING.md

**Comment by WangzoR** [comment]
https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/

**Comment by ianagbip1oti** [comment]
Guidelines for becoming an official lib: https://gist.github.com/meew0/bbbbd5348967dee5f7e84c0cd58983fd

**Comment by CoreyShupe** [comment]
Make sure to document the configuration well. Probably pretty important just because it's the main way to get things setup properly.
