### ISSUE TITLE
Support all Gateway Commands

### ISSUE THREAD

**Issue by ianagbip1oti** [princesslana/ErisCasper.java#122]
https://discordapp.com/developers/docs/topics/gateway#commands-and-events-gateway-commands

- [ ] Identify | triggers the initial handshake with the gateway
- [x] Resume | resumes a dropped gateway connection
- [ ] Heartbeat | maintains an active gateway connection
- [ ] Request Guild Members | requests offline members for a guild
- [ ] Update Voice State | joins, moves, or disconnects the client from a voice channel
- [ ] Update Status | updates a client's presence

**Comment by ianagbip1oti** [comment]
A couple of things TBD:
* Should Commands have a wrapper like Events do?
* Heartbeat is supported, but should probably be broken out into a class for consistency? https://github.com/princesslana/ErisCasper.java/blob/master/src/main/java/com/github/princesslana/eriscasper/gateway/Payloads.java#L32-L34

**Comment by CoreyShupe** [comment]
If you break out all the commands into separate classes they should be separate not inner classes (like resume and identify are currently inner classes which maybe should be broken out similar to how routes are setup) Also what would the command wrappers even look like? They don't really generate a response.

Although heartbeats shouldn't be separated imo since it's just a sequence number being passed, anything more would over complicate things. Especially since a heartbeat will never be sent by a user. Everything else being wrapped in a separate class has a use.
