### ISSUE TITLE
Support Channel Resource

### ISSUE THREAD

**Issue by ianagbip1oti** [princesslana/ErisCasper.java#124]
https://discordapp.com/developers/docs/resources/channel#channels-resource

- [x] Get Channel
- [x] Modify Channel
- [x] Delete/Close Channel
- [x] Get Channel Messages
- [x] Get Channel Message
- [ ] Create Message
- [x] Create Reaction
- [x] Delete Own Reaction
- [x] Delete User Reaction
- [x] Get Reactions
- [x] Delete All Reactions
- [x] Edit Message
- [x] Delete Message
- [x] Bulk Delete Messages
- [ ] Edit Channel Permissions
- [ ] Get Channel Invites
- [ ] Create Channel Invite
- [ ] Delete Channel Permission
- [ ] Trigger Typing Indicator
- [ ] Get Pinned Messages
- [ ] Add Pinned Channel Message
- [ ] Delete Pinned Channel Message
- [ ] Group DM Add Recipient
- [ ] Group DM Remove Recipient

We will not support the "Bulk Delete Messages (deprecated)" endpoint

**Comment by CoreyShupe** [comment]
Most of these have been completed besides `Get Channel Invites` due to the metadata implementation I'm not sure how to do. I'll PR it once my master branch gets merged just due to rebranching issues always pulling from master and trying to commit everything. Just didn't rebranch early enough.

**Comment by CoreyShupe** [comment]
Small update, found something to work with invites with metadata, I might change how it works later actually, but it works for now and works well, I don't think the metadata should be separated, changes will show up in `Data` with it. A lot of route changes will depend on changes in `Data`.

**Comment by CoreyShupe** [comment]
I unchecked CreateMessage just due to it being unfinished.

**Comment by ianagbip1oti** [comment]
This is all done in ErisCasper-Data now.
