### ISSUE TITLE
Support Emoji Resource

### ISSUE THREAD

**Issue by ianagbip1oti** [princesslana/ErisCasper.java#125]
https://discordapp.com/developers/docs/resources/emoji#emoji-resource

- [x] List Guild Emojis
- [x] Get Guild Emoji
- [x] Create Guild Emoji
- [x] Modify Guild Emoji
- [x] Delete Guild Emoji
