### ISSUE TITLE
Support Guild Resource

### ISSUE THREAD

**Issue by ianagbip1oti** [princesslana/ErisCasper.java#126]
https://discordapp.com/developers/docs/resources/guild#guild-resource

- [x] Create Guild
- [x] Get Guild
- [x] Modify Guild
- [x] Delete Guild
- [x] Get Guild Channels
- [x] Create Guild Channel
- [x] Modify Guild Channel Positions
- [x] Get Guild Member
- [x] List Guild Members
- [x] Add Guild Member
- [x] Modify Guild Member
- [x] Modify Current User Nick
- [x] Add Guild Member Role
- [x] Remove Guild Member Role
- [x] Remove Guild Member
- [x] Get Guild Bans
- [x] Create Guild Ban
- [x] Remove Guild Ban
- [x] Get Guild Roles
- [x] Create Guild Role
- [x] Modify Guild Role Positions
- [x] Modify Guild Role
- [x] Delete Guild Role
- [x] Get Guild Prune Count
- [x] Begin Guild Prune
- [x] Get Guild Voice Regions
- [x] Get Guild Invites
- [x] Get Guild Integrations
- [x] Create Guild Integration
- [x] Modify Guild Integration
- [x] Delete Guild Integration
- [x] Sync Guild Integration
- [x] Get Guild Embed
- [x] Modify Guild Embed
- [x] Get Guild Vanity URL
