### ISSUE TITLE
Support User Resource

### ISSUE THREAD

**Issue by ianagbip1oti** [princesslana/ErisCasper.java#128]
https://discordapp.com/developers/docs/resources/user#users-resource

- [x] Avatar Data
- [x] Usernames and Nicknames
- [x] Get Current User
- [x] Get User
- [x] Modify Current User
- [x] Get Current User Guilds
- [x] Leave Guild
- [x] Get User DMs
- [x] Create DM
- [x] Create Group DM
- [x] Get User Connections
